server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
    redis:
      host: localhost
      port: 6379

rt-service:
  redis:
    channel: realtime-topic

app:
  service:
    profile: http://localhost:8081/profile
    follow: http://localhost:8084/follow
