spring:
  application:
    name: interaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/INTERACTION
    username: admin123
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8087
  servlet:
    context-path: /interaction

app:
  service:
    profile: http://localhost:8081/profile
    media: http://localhost:8086
    post: http://localhost:8085/post