spring:
  application:
    name: post-service

  cloud:
    openfeign:
      client:
        config:
          ai-service:
            connect-timeout: 10000
            read-timeout: 60000

  datasource:
    url: jdbc:postgresql://localhost:5432/POST
    username: admin123
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

server:
  port: 8085
  servlet:
    context-path: /post

app:
  service:
    profile: http://localhost:8081/profile
    media: http://localhost:8086
    interaction: http://localhost:8087/interaction
    ai: http://localhost:8092
    follow: http://localhost:8084/follow
    group: http://localhost:8093/group
    notification: http://localhost:8082/notification
  geo:
    ipinfo-token: e9580fb14a1286
    # test chạy localhost
    dev-fallback-ip: 113.161.80.1
    #dev-fallback-ip: 113.160.0.0

deepl:
  api-key: 12e45efd-869f-4b58-8043-aaf7689aa828:fx

cloud:
  openfeign:
    client:
      config:
        ai-service:
          connect-timeout: 50000
          read-timeout: 120000