spring:
  application:
    name: post-service

  datasource:
    url: jdbc:postgresql://localhost:5432/POST
    username: admin123
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085
  servlet:
    context-path: /post

app:
  service:
    profile: http://localhost:8081/profile
    media: http://localhost:8086
    interaction: http://localhost:8087/interaction