spring:
  application:
    name: media-service

  datasource:
    url: jdbc:postgresql://localhost:5432/MEDIA
    username: admin123
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cloudinary:
  cloud_name: dfscz2c2l
  api_key: 176445729432524
  api_secret: mki6bPZ7weHEuJ3pRK4yHAEyEqg

server:
  port: 8086